# Generate a .cpp that embeds the bytes of INPUT as a std::string_view named SYMBOL.
#
# Usage:
#   cmake -DINPUT=<path/to/file.html> -DOUTPUT=<path/to/out.cpp> \
#         -DSYMBOL=kEmbeddedIndexHtml -DHEADER=embedded_index_html.hpp \
#         -P embed_html.cmake
#
# The generated file includes <HEADER> (no path prefix) and defines:
#   namespace phc { extern const std::string_view SYMBOL; }
# with the bytes from INPUT.

if(NOT INPUT)
  message(FATAL_ERROR "embed_html.cmake: INPUT not set")
endif()
if(NOT OUTPUT)
  message(FATAL_ERROR "embed_html.cmake: OUTPUT not set")
endif()
if(NOT SYMBOL)
  message(FATAL_ERROR "embed_html.cmake: SYMBOL not set")
endif()
if(NOT HEADER)
  message(FATAL_ERROR "embed_html.cmake: HEADER not set")
endif()

file(READ "${INPUT}" hex HEX)

# Insert a comma after every byte: "3c21..." -> "0x3c,0x21,..."
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
# Wrap every 16 bytes for readability.
string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")

set(out
"// AUTO-GENERATED by cpp/cmake/embed_html.cmake. Do not edit.
// Source: ${INPUT}

#include \"${HEADER}\"

namespace phc {

namespace {
constexpr unsigned char kBytes[] = {
    ${bytes}
};
}  // namespace

const std::string_view ${SYMBOL}(
    reinterpret_cast<const char*>(kBytes), sizeof(kBytes));

}  // namespace phc
")

# Ensure parent directory exists when OUTPUT is nested (e.g. build/generated/...).
get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
if(output_dir)
  file(MAKE_DIRECTORY "${output_dir}")
endif()

file(WRITE "${OUTPUT}" "${out}")
